project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Intro"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "Others"
        href: others.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css