project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Intro"
        href: index.html
      - text: "About"
        href: about.html
      - text: "Publications"
        href: publications.html
      - text: "Outreach"
        href: outreach.html
      - text: "Others"
        href: others.html
    

format:
  html:
    theme: cosmo
    css: styles.css